name: FTP Deploy

on: [push] # 触发事件，这里设置为每次push时触发

jobs:
  deploy:
    runs-on: ubuntu-latest # 运行环境

    steps:
    - uses: actions/checkout@v2 # 检出仓库

    - name: 部署到FTP服务器
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }} # FTP服务器地址
        username: ${{ secrets.FTP_USERNAME }} # FTP用户名
        password: ${{ secrets.FTP_PASSWORD }} # FTP密码
        local-dir: ./ # 本地目录，这里表示当前仓库根目录
        remote-dir: / # 远程目录，根据实际情况修改
